version: "3.2"
services:
  web:
    image: cc17g2/image_frontend
    deploy:
        replicas: 2
        placement:
            constraints:
                - node.hostname == ccg2-a3-stack-frontend
        restart_policy:
            condition: on-failure
    ports:
        - "80:80"
    volumes:
        - /etc:/hypervisor_etc
    
    environment:
        - CC_BACKEND_SERVERS=${CC_BACKEND_SERVERS}
  

