version: "3.2"
services:
  web:
    image: cc17g2/image_backend
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.hostname != ccg2-a3-stack-frontend
    ports:
      - "8000:80"
    volumes:
      - /etc:/hypervisor_etc
        